global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "express-otel-metrics"
    static_configs:
      - targets: ["docker.for.mac.host.internal:8080"]
remote_write:
  - url: <remote_write_url>
    bearer_token: <redacted>
